import { SupplierCategory, Certification } from '@prisma/client'

export const suppliers = [
  {
    companyName: 'Graceful Monkey',
    slug: 'graceful-monkey',
    tagline: 'Studio creating Digital Content & Experiences',
    description: 'Creative studio specializing in digital content creation and immersive brand experiences for the drinks industry. We help brands tell their stories through compelling visual content.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Video Production', 'Photography', 'Digital Experiences', 'Social Content'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Buddy Creative',
    slug: 'buddy-creative',
    tagline: 'Brand and packaging design agency specialising in food & drink',
    description: 'Award-winning brand and packaging design agency with deep expertise in the food and drink sector. We create distinctive brand identities that stand out on shelf and connect with consumers.',
    category: 'DESIGN' as SupplierCategory,
    services: ['Brand Identity', 'Packaging Design', 'Label Design', 'Brand Strategy'],
    location: 'Manchester',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe', 'North America'],
    isVerified: true,
  },
  {
    companyName: 'Bien Venue Ltd',
    slug: 'bien-venue',
    tagline: 'Free service sourcing standout venues for drinks brands',
    description: 'Specialist venue sourcing service helping drinks brands find the perfect locations for launches, tastings, and events. Our service is completely free for brands.',
    category: 'OTHER' as SupplierCategory,
    services: ['Venue Sourcing', 'Event Planning', 'Launch Events', 'Brand Activations'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'AM Distilling LTD',
    slug: 'am-distilling',
    tagline: 'Contract Bottlers/Contract Blenders/Bulk Spirits',
    description: 'Full-service contract distilling, blending, and bottling facility. We work with brands of all sizes to bring their spirits to market with quality and consistency.',
    category: 'CO_PACKING' as SupplierCategory,
    services: ['Contract Distilling', 'Contract Bottling', 'Blending', 'Bulk Spirits'],
    location: 'Scotland',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    moqMin: 500,
    isVerified: true,
  },
  {
    companyName: 'Eventism Ltd',
    slug: 'eventism',
    tagline: 'Events consultancy specialising in shows for the drinks industry',
    description: 'Expert events consultancy helping drinks brands maximize their presence at trade shows and consumer events. We handle everything from stand design to staffing.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Trade Show Management', 'Event Consultancy', 'Stand Design', 'Staffing'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'SAVERGLASS',
    slug: 'saverglass',
    tagline: 'Premium glass bottles, bespoke and off-the-shelf',
    description: 'World-leading manufacturer of premium glass bottles for spirits, wine, and beverages. Offering both bespoke designs and an extensive catalog of ready-made options.',
    category: 'PACKAGING' as SupplierCategory,
    services: ['Glass Bottles', 'Bespoke Design', 'Premium Packaging', 'Decoration'],
    location: 'France',
    country: 'France',
    serviceRegions: ['United Kingdom', 'Europe', 'North America', 'Global'],
    moqMin: 5000,
    certifications: ['OTHER'] as Certification[],
    isVerified: true,
  },
  {
    companyName: 'Astute Beverages',
    slug: 'astute-beverages',
    tagline: 'Non-Alcoholic Beverage Export Market Specialist',
    description: 'Specialist export agency focused on non-alcoholic and low-alcohol beverages. We help brands expand into international markets with our deep network of buyers and distributors.',
    category: 'DISTRIBUTION' as SupplierCategory,
    services: ['Export Services', 'Market Entry', 'Buyer Introductions', 'Trade Support'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['Europe', 'Middle East', 'Asia', 'North America'],
    isVerified: true,
  },
  {
    companyName: 'Supplychain21 Ltd',
    slug: 'supplychain21',
    tagline: 'Transport services to the Drinks Industry',
    description: 'Dedicated logistics provider for the drinks industry. We understand the unique requirements of beverage transport and offer reliable, temperature-controlled solutions.',
    category: 'LOGISTICS' as SupplierCategory,
    services: ['Transport', 'Warehousing', 'Distribution', 'Temperature Control'],
    location: 'Birmingham',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'BB Comms',
    slug: 'bb-comms',
    tagline: 'Spirits specialist PR, events and marketing consultancy',
    description: 'Boutique PR and marketing agency exclusively focused on the spirits industry. We build brand awareness through strategic media relations, events, and digital campaigns.',
    category: 'MARKETING' as SupplierCategory,
    services: ['PR', 'Media Relations', 'Events', 'Marketing Strategy'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Kind Community',
    slug: 'kind-community',
    tagline: 'Help kind companies grow impactful brands through communities',
    description: 'Community-building specialists helping purpose-driven drinks brands grow through authentic community engagement and grassroots marketing.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Community Building', 'Brand Advocacy', 'Grassroots Marketing', 'Social Impact'],
    location: 'Bristol',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    certifications: ['B_CORP'] as Certification[],
    isVerified: true,
  },
  {
    companyName: 'HighSpirit Agency',
    slug: 'highspirit-agency',
    tagline: 'Brand identity, packaging, campaigns, social creative, digital',
    description: 'Full-service creative agency for drinks brands. From brand identity to social media campaigns, we deliver cohesive creative that drives growth.',
    category: 'DESIGN' as SupplierCategory,
    services: ['Brand Identity', 'Packaging Design', 'Social Media', 'Digital Marketing'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe', 'North America'],
    isVerified: true,
  },
  {
    companyName: 'Red Distillery',
    slug: 'red-distillery',
    tagline: 'Deliver comprehensive 360-degree service to drinks industry',
    description: 'Full-service partner for drinks brands offering distilling, bottling, warehousing, and fulfillment all under one roof. Your one-stop shop for production.',
    category: 'CO_PACKING' as SupplierCategory,
    services: ['Contract Distilling', 'Bottling', 'Warehousing', 'Fulfillment'],
    location: 'Wales',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    moqMin: 200,
    isVerified: true,
  },
  {
    companyName: 'B2C Group Ltd',
    slug: 'b2c-group',
    tagline: 'Build, Optimise and Scale premium brands on Amazon',
    description: 'Amazon specialists helping premium drinks brands succeed on the world\'s largest marketplace. We handle everything from listing optimization to advertising.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Amazon Management', 'Listing Optimization', 'PPC Advertising', 'Brand Registry'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe', 'North America'],
    isVerified: true,
  },
  {
    companyName: 'Scale Drinks',
    slug: 'scale-drinks',
    tagline: 'Export Agency - Maximise your global potential',
    description: 'International export agency helping UK drinks brands expand globally. We provide market insights, buyer connections, and hands-on support for market entry.',
    category: 'DISTRIBUTION' as SupplierCategory,
    services: ['Export Services', 'Market Research', 'Buyer Connections', 'Market Entry'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['Europe', 'Asia', 'North America', 'Australia'],
    isVerified: true,
  },
  {
    companyName: 'Label Apeel Ltd',
    slug: 'label-apeel',
    tagline: "UK's Best Label Manufacturer",
    description: 'Premium label manufacturer specializing in the drinks industry. We offer a wide range of finishes, materials, and techniques to make your bottles stand out.',
    category: 'PACKAGING' as SupplierCategory,
    services: ['Label Printing', 'Foil Labels', 'Textured Labels', 'Sustainable Labels'],
    location: 'Nottingham',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    moqMin: 1000,
    isVerified: true,
  },
  {
    companyName: 'DIGLIS Consulting',
    slug: 'diglis-consulting',
    tagline: 'Global Recruitment Experts for Consumer Goods Industry',
    description: 'Specialist recruitment consultancy for the drinks and consumer goods industry. We find exceptional talent for brands at every stage of growth.',
    category: 'CONSULTING' as SupplierCategory,
    services: ['Executive Search', 'Recruitment', 'Talent Advisory', 'HR Consulting'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe', 'Global'],
    isVerified: true,
  },
  {
    companyName: 'Marillier Consulting',
    slug: 'marillier-consulting',
    tagline: 'Consulting for strategy, finance, distribution to unlock growth',
    description: 'Strategic consultancy helping drinks brands scale through better strategy, financial planning, and distribution optimization.',
    category: 'CONSULTING' as SupplierCategory,
    services: ['Strategy', 'Financial Planning', 'Distribution Strategy', 'Growth Advisory'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'DrincX Ltd',
    slug: 'drincx',
    tagline: 'Brand management, business development & consulting',
    description: 'Boutique consultancy offering brand management and business development services to drinks brands looking to accelerate growth.',
    category: 'CONSULTING' as SupplierCategory,
    services: ['Brand Management', 'Business Development', 'Sales Strategy', 'Market Entry'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Aitch Creates',
    slug: 'aitch-creates',
    tagline: 'Strategic branding and design for ambitious drinks brands',
    description: 'Design studio creating bold, strategic branding for drinks brands ready to make an impact. We combine creativity with commercial thinking.',
    category: 'DESIGN' as SupplierCategory,
    services: ['Brand Strategy', 'Visual Identity', 'Packaging Design', 'Brand Guidelines'],
    location: 'Edinburgh',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Lucie Rhoades Comms',
    slug: 'lucie-rhoades-comms',
    tagline: 'Copywriting and brand consultancy',
    description: 'Specialist copywriter and brand consultant for drinks brands. From bottle copy to brand stories, we craft words that sell.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Copywriting', 'Brand Story', 'Tone of Voice', 'Content Strategy'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe', 'Global'],
    isVerified: true,
  },
  {
    companyName: 'Anderson Cole Group',
    slug: 'anderson-cole-group',
    tagline: 'Freelance recruiter for growing FMCG Brands',
    description: 'Specialist recruiter helping growing FMCG and drinks brands find the talent they need to scale.',
    category: 'CONSULTING' as SupplierCategory,
    services: ['Recruitment', 'Talent Search', 'Contract Staffing', 'HR Advisory'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Addition',
    slug: 'addition',
    tagline: 'Accounting & CFO Platform for FMCG/Ecom businesses',
    description: 'Modern accounting platform built for FMCG and e-commerce brands. Get real-time financial insights and fractional CFO support.',
    category: 'FINANCE' as SupplierCategory,
    services: ['Accounting', 'Fractional CFO', 'Financial Reporting', 'Cash Flow Management'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'The Custom Spirit Co',
    slug: 'custom-spirit-co',
    tagline: 'Contract distilling, blending, fermentation and bottling',
    description: 'Flexible contract distillery offering distilling, blending, fermentation, and bottling services. Perfect for brands of all sizes.',
    category: 'CO_PACKING' as SupplierCategory,
    services: ['Contract Distilling', 'Blending', 'Fermentation', 'Bottling'],
    location: 'England',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    moqMin: 100,
    isVerified: true,
  },
  {
    companyName: 'Cone Accounting Limited',
    slug: 'cone-accounting',
    tagline: 'Accounting, bookkeeping, reporting and virtual CFO services',
    description: 'Accounting firm specializing in drinks and hospitality businesses. We provide clear financial insights to help you grow.',
    category: 'FINANCE' as SupplierCategory,
    services: ['Accounting', 'Bookkeeping', 'Virtual CFO', 'Tax Planning'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Bostocap SRL',
    slug: 'bostocap',
    tagline: 'Bottle Stoppers and Capsules',
    description: 'Specialist manufacturer of premium bottle closures, stoppers, and capsules for spirits and wine. Italian craftsmanship meets innovation.',
    category: 'PACKAGING' as SupplierCategory,
    services: ['Cork Stoppers', 'Capsules', 'Closures', 'Custom Solutions'],
    location: 'Italy',
    country: 'Italy',
    serviceRegions: ['United Kingdom', 'Europe', 'Global'],
    moqMin: 5000,
    isVerified: true,
  },
  {
    companyName: 'Cocktail Connoisseurs',
    slug: 'cocktail-connoisseurs',
    tagline: 'Bespoke Cocktail & Drinks Boxes for PR, Activations & Retail',
    description: 'Creator of premium cocktail boxes and gift sets for PR sampling, brand activations, and retail. Make your brand unforgettable.',
    category: 'PACKAGING' as SupplierCategory,
    services: ['Gift Boxes', 'PR Boxes', 'Retail Packaging', 'Brand Activations'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    moqMin: 50,
    isVerified: true,
  },
  {
    companyName: 'SBP Events LTD',
    slug: 'sbp-events',
    tagline: 'Books and negotiates stands at 150+ consumer shows UK/Ireland',
    description: 'Event booking specialists handling stand bookings and negotiations at over 150 consumer shows across the UK and Ireland.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Stand Booking', 'Event Negotiation', 'Show Planning', 'Exhibitor Support'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Ireland'],
    isVerified: true,
  },
  {
    companyName: 'Iconic Distro Company Ltd',
    slug: 'iconic-distro',
    tagline: 'D2C fulfillment and Amazon management for drinks brands',
    description: 'E-commerce fulfillment specialist for drinks brands. We handle D2C shipping and Amazon FBA management so you can focus on growth.',
    category: 'LOGISTICS' as SupplierCategory,
    services: ['D2C Fulfillment', 'Amazon FBA', 'Warehousing', 'Order Management'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Frederick Wilkinson',
    slug: 'frederick-wilkinson',
    tagline: 'Photography and videography for drinks brands',
    description: 'Professional photographer and videographer specializing in drinks brands. Beautiful imagery that captures your brand\'s essence.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Photography', 'Videography', 'Product Shots', 'Lifestyle Content'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Greenbox Designs',
    slug: 'greenbox-designs',
    tagline: 'Website developers - builders of this website',
    description: 'Web development agency specializing in drinks brands. We build beautiful, high-converting websites that tell your brand story.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Web Design', 'Web Development', 'E-commerce', 'Digital Strategy'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe', 'Global'],
    isVerified: true,
  },
  {
    companyName: 'Easy Chew',
    slug: 'easy-chew',
    tagline: 'Paid ads for social media and search platforms',
    description: 'Performance marketing agency for drinks brands. We drive sales through targeted paid advertising on social media and search.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Paid Social', 'Google Ads', 'Performance Marketing', 'Campaign Management'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Halo Business Support Ltd',
    slug: 'halo-business-support',
    tagline: 'Back-office logistics and customer service support',
    description: 'Outsourced back-office support for drinks brands. We handle logistics coordination and customer service so you can focus on growth.',
    category: 'LOGISTICS' as SupplierCategory,
    services: ['Customer Service', 'Logistics Coordination', 'Order Processing', 'Back Office'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Giraffe Distillers Ltd',
    slug: 'giraffe-distillers',
    tagline: 'Sustainable bottling and distilling for spirits',
    description: 'Sustainability-focused contract distillery offering eco-friendly bottling and distilling services for spirits brands.',
    category: 'CO_PACKING' as SupplierCategory,
    services: ['Contract Distilling', 'Sustainable Bottling', 'NPD', 'Blending'],
    location: 'England',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    certifications: ['CARBON_NEUTRAL'] as Certification[],
    moqMin: 200,
    isVerified: true,
  },
  {
    companyName: 'Cooper Parry',
    slug: 'cooper-parry',
    tagline: 'Accountancy services for drinks businesses',
    description: 'Top 20 UK accountancy firm with dedicated expertise in drinks and hospitality businesses. Strategic financial advice for growth.',
    category: 'FINANCE' as SupplierCategory,
    services: ['Accounting', 'Tax Advisory', 'Audit', 'Business Advisory'],
    location: 'Midlands',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Berlin Packaging',
    slug: 'berlin-packaging',
    tagline: 'Global packaging solutions in glass, plastic, and metal',
    description: 'Global packaging supplier offering comprehensive solutions in glass, plastic, and metal packaging for beverages of all types.',
    category: 'PACKAGING' as SupplierCategory,
    services: ['Glass Packaging', 'Plastic Packaging', 'Metal Packaging', 'Custom Design'],
    location: 'Multiple Locations',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe', 'North America', 'Global'],
    moqMin: 1000,
    isVerified: true,
  },
  {
    companyName: 'Orange by Marmalade',
    slug: 'orange-marmalade',
    tagline: 'Brand strategy and design for drinks brands',
    description: 'Strategic branding agency creating distinctive identities for drinks brands. From strategy to execution, we build brands that sell.',
    category: 'DESIGN' as SupplierCategory,
    services: ['Brand Strategy', 'Brand Identity', 'Packaging Design', 'Brand Positioning'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Cleverdrinks Photography',
    slug: 'cleverdrinks-photography',
    tagline: 'Photography and videography for drinks brands',
    description: 'Specialist drinks photographer creating stunning imagery for bottles, cocktails, and lifestyle content.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Product Photography', 'Cocktail Photography', 'Video Content', 'Lifestyle Shoots'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'MAFFEO DRINKS s.r.o.',
    slug: 'maffeo-drinks',
    tagline: 'Commercial and marketing advisory for drinks brands',
    description: 'International drinks consultancy offering commercial strategy and marketing advisory services across European markets.',
    category: 'CONSULTING' as SupplierCategory,
    services: ['Commercial Strategy', 'Marketing Advisory', 'Market Entry', 'Sales Strategy'],
    location: 'Prague',
    country: 'Czech Republic',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Nightcap Brands',
    slug: 'nightcap-brands',
    tagline: 'Sales agency for premium drinks in on-trade and retail',
    description: 'Premium drinks sales agency with strong relationships in on-trade and retail. We get your brand on the right shelves and back bars.',
    category: 'DISTRIBUTION' as SupplierCategory,
    services: ['Sales Agency', 'On-Trade Sales', 'Retail Sales', 'Account Management'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Nolen Consultancy',
    slug: 'nolen-consultancy',
    tagline: 'Drinks industry consultancy for sales and digital solutions',
    description: 'Consultancy helping drinks brands optimize their sales strategies and digital presence for maximum impact.',
    category: 'CONSULTING' as SupplierCategory,
    services: ['Sales Consulting', 'Digital Strategy', 'E-commerce', 'Market Analysis'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Bobbys Gin Distribution BV',
    slug: 'bobbys-gin-distribution',
    tagline: 'Gin, jenever, and ready-to-drink cocktails distribution',
    description: 'Specialist distributor focused on gin, jenever, and RTD cocktails. Strong network across Benelux and expanding.',
    category: 'DISTRIBUTION' as SupplierCategory,
    services: ['Distribution', 'Import/Export', 'Market Development', 'Trade Marketing'],
    location: 'Netherlands',
    country: 'Netherlands',
    serviceRegions: ['Netherlands', 'Belgium', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Seven Sages',
    slug: 'seven-sages',
    tagline: 'Marketing, design, and editing for drinks brands',
    description: 'Creative agency offering marketing strategy, design services, and content editing for drinks brands.',
    category: 'DESIGN' as SupplierCategory,
    services: ['Marketing Strategy', 'Graphic Design', 'Content Editing', 'Campaign Creative'],
    location: 'Ireland',
    country: 'Ireland',
    serviceRegions: ['United Kingdom', 'Ireland', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'This is Undefined',
    slug: 'this-is-undefined',
    tagline: 'Website design and digital products for drinks brands',
    description: 'Digital agency building beautiful websites and digital products for drinks brands. Modern, fast, and conversion-focused.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Web Design', 'Digital Products', 'E-commerce', 'UX Design'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe', 'Global'],
    isVerified: true,
  },
  {
    companyName: 'Hensol Castle Distillery',
    slug: 'hensol-castle-distillery',
    tagline: 'Contract bottling, distilling, and NPD for drinks',
    description: 'Historic Welsh distillery offering contract production services including distilling, bottling, and new product development.',
    category: 'CO_PACKING' as SupplierCategory,
    services: ['Contract Distilling', 'Bottling', 'NPD', 'Recipe Development'],
    location: 'Wales',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    moqMin: 300,
    isVerified: true,
  },
  {
    companyName: 'Cutlass Communications',
    slug: 'cutlass-communications',
    tagline: 'PR, events, and marketing for drinks brands',
    description: 'Full-service communications agency for drinks brands. From PR to events to digital marketing, we amplify your brand.',
    category: 'MARKETING' as SupplierCategory,
    services: ['PR', 'Events', 'Marketing', 'Influencer Relations'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Dimax Digital',
    slug: 'dimax-digital',
    tagline: 'Digital marketing and brand development for drinks',
    description: 'Digital-first marketing agency helping drinks brands build awareness and drive sales through strategic online campaigns.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Digital Marketing', 'Social Media', 'Brand Development', 'Content Marketing'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Smurfit Westrock Saxon',
    slug: 'smurfit-westrock-saxon',
    tagline: 'Corrugated boxes for drinks packaging',
    description: 'Leading manufacturer of corrugated packaging solutions for the drinks industry. From shipping boxes to premium display cases.',
    category: 'PACKAGING' as SupplierCategory,
    services: ['Corrugated Boxes', 'Display Packaging', 'Shipping Solutions', 'Custom Packaging'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    moqMin: 500,
    isVerified: true,
  },
  {
    companyName: 'The Advocate Group',
    slug: 'advocate-group',
    tagline: 'Recruitment and marketing campaigns for drinks brands',
    description: 'Dual-service agency offering both recruitment solutions and marketing campaign management for drinks brands.',
    category: 'CONSULTING' as SupplierCategory,
    services: ['Recruitment', 'Marketing Campaigns', 'Brand Ambassadors', 'Field Marketing'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'BBJ&K',
    slug: 'bbjk',
    tagline: 'Paid media and digital advertising for drinks brands',
    description: 'Performance marketing specialists driving growth for drinks brands through paid media and digital advertising.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Paid Media', 'Digital Advertising', 'Performance Marketing', 'Analytics'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Partner Up',
    slug: 'partner-up',
    tagline: 'Platform for drinks brands to collaborate on marketing',
    description: 'Collaboration platform connecting drinks brands for joint marketing initiatives, cross-promotions, and partnerships.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Brand Partnerships', 'Cross-Promotion', 'Collaboration Platform', 'Marketing'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Soho Drinks Ltd',
    slug: 'soho-drinks',
    tagline: 'PR services to elevate drinks and lifestyle brands',
    description: 'Soho-based PR agency elevating drinks and lifestyle brands through strategic media relations and influencer partnerships.',
    category: 'MARKETING' as SupplierCategory,
    services: ['PR', 'Media Relations', 'Influencer Marketing', 'Brand Partnerships'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Midday Studio',
    slug: 'midday-studio',
    tagline: 'Award-winning design for food and drink brands',
    description: 'Award-winning design studio creating distinctive brand identities and packaging for food and drink brands.',
    category: 'DESIGN' as SupplierCategory,
    services: ['Brand Identity', 'Packaging Design', 'Art Direction', 'Visual Strategy'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe', 'Global'],
    isVerified: true,
  },
  {
    companyName: 'On A Plate Growth',
    slug: 'on-a-plate-growth',
    tagline: 'Email marketing, CRM, and DTC sales growth for drinks',
    description: 'Growth marketing agency specializing in email, CRM, and DTC sales optimization for drinks brands.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Email Marketing', 'CRM', 'DTC Growth', 'Retention Marketing'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Spirited Marketing',
    slug: 'spirited-marketing',
    tagline: 'Marketing for spirits and premium drinks brands',
    description: 'Marketing consultancy dedicated to spirits and premium drinks brands. We create campaigns that resonate with discerning consumers.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Marketing Strategy', 'Campaign Development', 'Brand Positioning', 'Trade Marketing'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Tortuga',
    slug: 'tortuga',
    tagline: 'UK distribution and back-office logistics for drinks brands',
    description: 'Full-service distribution partner for drinks brands in the UK. From warehousing to delivery, we handle your logistics.',
    category: 'LOGISTICS' as SupplierCategory,
    services: ['Distribution', 'Warehousing', 'Order Fulfillment', 'Back-Office Support'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'London City Bond Ltd',
    slug: 'london-city-bond',
    tagline: 'Bonded warehouse storage and UK-wide delivery',
    description: 'Bonded warehousing specialist offering secure storage and UK-wide delivery services for drinks brands.',
    category: 'LOGISTICS' as SupplierCategory,
    services: ['Bonded Storage', 'Warehousing', 'UK Delivery', 'Duty Management'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Pear & Sons Production Studio',
    slug: 'pear-sons-studio',
    tagline: 'Visual assets for food and drink brands',
    description: 'Production studio creating premium visual assets for food and drink brands. Photography, video, and CGI.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Photography', 'Video Production', 'CGI', 'Visual Content'],
    location: 'London',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Crate PR',
    slug: 'crate-pr',
    tagline: 'PR, marketing, and influencer engagement for drinks brands',
    description: 'PR and marketing agency helping drinks brands build awareness through media coverage and influencer partnerships.',
    category: 'MARKETING' as SupplierCategory,
    services: ['PR', 'Marketing', 'Influencer Engagement', 'Media Relations'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Clyde Presentation Packaging',
    slug: 'clyde-presentation-packaging',
    tagline: 'Bespoke presentation packaging for drinks brands',
    description: 'Specialist in premium presentation packaging for drinks brands. Gift boxes, cases, and bespoke solutions.',
    category: 'PACKAGING' as SupplierCategory,
    services: ['Gift Boxes', 'Presentation Cases', 'Bespoke Packaging', 'Luxury Packaging'],
    location: 'Glasgow',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    moqMin: 100,
    isVerified: true,
  },
  {
    companyName: 'Bottled and Canned',
    slug: 'bottled-and-canned',
    tagline: 'Specialist contract canning for drinks brands',
    description: 'Mobile and fixed-site contract canning specialists for craft beverages. From RTDs to craft beer.',
    category: 'CO_PACKING' as SupplierCategory,
    services: ['Contract Canning', 'Mobile Canning', 'RTD Production', 'Quality Control'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    moqMin: 500,
    isVerified: true,
  },
  {
    companyName: 'Bowimi',
    slug: 'bowimi',
    tagline: 'CRM/sales platform for drinks brands to boost efficiency',
    description: 'Purpose-built CRM and sales platform for drinks brands. Manage your on-trade relationships and orders efficiently.',
    category: 'OTHER' as SupplierCategory,
    services: ['CRM Platform', 'Sales Management', 'Order Management', 'Customer Analytics'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Avallen Solutions',
    slug: 'avallen-solutions',
    tagline: 'Sustainability strategy and support for drinks brands',
    description: 'Sustainability consultancy helping drinks brands reduce their environmental impact and communicate their green credentials.',
    category: 'CONSULTING' as SupplierCategory,
    services: ['Sustainability Strategy', 'Carbon Footprint', 'B-Corp Support', 'Green Marketing'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    certifications: ['B_CORP', 'CARBON_NEUTRAL'] as Certification[],
    isVerified: true,
  },
  {
    companyName: 'Flourish Creative',
    slug: 'flourish-creative',
    tagline: 'Vibrant photography and video content for drinks brands',
    description: 'Creative studio producing vibrant, eye-catching photography and video content for drinks brands.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Photography', 'Video Content', 'Social Content', 'Campaign Creative'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'Verallia',
    slug: 'verallia',
    tagline: 'UK-made glass bottles, bespoke and off-the-shelf',
    description: 'Major glass manufacturer producing bottles in the UK. Extensive catalog plus bespoke design capabilities.',
    category: 'PACKAGING' as SupplierCategory,
    services: ['Glass Bottles', 'Bespoke Design', 'Sustainable Glass', 'Decoration'],
    location: 'Yorkshire',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    moqMin: 10000,
    certifications: ['CARBON_NEUTRAL'] as Certification[],
    isVerified: true,
  },
  {
    companyName: 'Jamie Prowse Freelance',
    slug: 'jamie-prowse-freelance',
    tagline: 'Amazon optimization and advertising for drinks brands',
    description: 'Freelance Amazon specialist helping drinks brands optimize their presence and advertising on Amazon.',
    category: 'MARKETING' as SupplierCategory,
    services: ['Amazon Optimization', 'PPC Management', 'Listing Optimization', 'Brand Content'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    isVerified: true,
  },
  {
    companyName: 'The Brand Weaver',
    slug: 'brand-weaver',
    tagline: 'Brand strategy, consultancy, and design for breweries',
    description: 'Brand consultancy specializing in craft breweries and drinks brands. From strategy to visual identity.',
    category: 'DESIGN' as SupplierCategory,
    services: ['Brand Strategy', 'Brand Consultancy', 'Visual Identity', 'Packaging'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Propak UK',
    slug: 'propak-uk',
    tagline: 'Luxury branded packaging for drinks brands',
    description: 'Premium packaging supplier creating luxury branded packaging solutions for drinks brands.',
    category: 'PACKAGING' as SupplierCategory,
    services: ['Luxury Packaging', 'Gift Sets', 'Branded Packaging', 'Custom Solutions'],
    location: 'United Kingdom',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom', 'Europe'],
    moqMin: 250,
    isVerified: true,
  },
  {
    companyName: 'DRG - Donald Reid Group',
    slug: 'drg-donald-reid',
    tagline: 'Accountancy and advisory for F&B startups and brands',
    description: 'Accountancy firm with dedicated expertise in food and beverage startups. From seed stage to scale-up.',
    category: 'FINANCE' as SupplierCategory,
    services: ['Accounting', 'Tax Advisory', 'Startup Finance', 'Growth Planning'],
    location: 'Scotland',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    isVerified: true,
  },
  {
    companyName: 'Burlington Bottling Co',
    slug: 'burlington-bottling',
    tagline: 'Contract bottling services for drinks brands',
    description: 'Contract bottling facility offering flexible bottling services for spirits, wine, and beverages.',
    category: 'CO_PACKING' as SupplierCategory,
    services: ['Contract Bottling', 'Labeling', 'Quality Control', 'Storage'],
    location: 'England',
    country: 'United Kingdom',
    serviceRegions: ['United Kingdom'],
    moqMin: 500,
    isVerified: true,
  },
]
