export const members: Array<{
  firstName: string
  lastName: string
  jobTitle: string
  company: string
  companyType: 'BRAND' | 'SUPPLIER'
  bio: string
  location: string
}> = [
  {
    firstName: 'Sarah',
    lastName: 'Mitchell',
    jobTitle: 'Founder & CEO',
    company: 'Tarquin\'s Gin',
    companyType: 'BRAND',
    bio: 'Pioneering Cornish distiller bringing traditional methods to modern gin making.',
    location: 'Cornwall',
  },
  {
    firstName: 'James',
    lastName: 'Cooper',
    jobTitle: 'Managing Director',
    company: 'Scale Drinks',
    companyType: 'SUPPLIER',
    bio: 'Helping UK drinks brands expand into international markets.',
    location: 'London',
  },
  {
    firstName: 'Emma',
    lastName: 'Thompson',
    jobTitle: 'Brand Director',
    company: 'Lucky Saint',
    companyType: 'BRAND',
    bio: 'Building the future of alcohol-free beer, one pint at a time.',
    location: 'London',
  },
  {
    firstName: 'David',
    lastName: 'Chen',
    jobTitle: 'UK Sales Manager',
    company: 'Berlin Packaging',
    companyType: 'SUPPLIER',
    bio: 'Connecting brands with innovative packaging solutions.',
    location: 'Manchester',
  },
  {
    firstName: 'Lucy',
    lastName: 'Williams',
    jobTitle: 'Founder',
    company: 'BB Comms',
    companyType: 'SUPPLIER',
    bio: 'Spirits PR specialist with 15 years of industry experience.',
    location: 'London',
  },
  {
    firstName: 'Tom',
    lastName: 'Richards',
    jobTitle: 'Head of Marketing',
    company: 'Chapel Down',
    companyType: 'BRAND',
    bio: 'Putting English wine on the world stage.',
    location: 'Kent',
  },
  {
    firstName: 'Rachel',
    lastName: 'Green',
    jobTitle: 'Creative Director',
    company: 'Buddy Creative',
    companyType: 'SUPPLIER',
    bio: 'Designing brands that stand out on shelf and in mind.',
    location: 'Manchester',
  },
  {
    firstName: 'Michael',
    lastName: 'Foster',
    jobTitle: 'Co-Founder',
    company: 'Seedlip',
    companyType: 'BRAND',
    bio: 'Revolutionizing what it means to drink without alcohol.',
    location: 'London',
  },
  {
    firstName: 'Anna',
    lastName: 'Peters',
    jobTitle: 'Operations Director',
    company: 'Iconic Distro',
    companyType: 'SUPPLIER',
    bio: 'Making D2C fulfillment seamless for drinks brands.',
    location: 'London',
  },
  {
    firstName: 'Chris',
    lastName: 'Baker',
    jobTitle: 'Master Distiller',
    company: 'Nc\'nean Distillery',
    companyType: 'BRAND',
    bio: 'Crafting organic whisky on the wild Scottish coast.',
    location: 'Scotland',
  },
  {
    firstName: 'Sophie',
    lastName: 'Turner',
    jobTitle: 'Account Director',
    company: 'SAVERGLASS',
    companyType: 'SUPPLIER',
    bio: 'Helping brands find their perfect bottle.',
    location: 'London',
  },
  {
    firstName: 'Alex',
    lastName: 'Morrison',
    jobTitle: 'Founder',
    company: 'Toast Ale',
    companyType: 'BRAND',
    bio: 'Fighting food waste one pint at a time.',
    location: 'London',
  },
  {
    firstName: 'Hannah',
    lastName: 'Clarke',
    jobTitle: 'Head of Growth',
    company: 'Addition',
    companyType: 'SUPPLIER',
    bio: 'Modern finance for modern drinks brands.',
    location: 'London',
  },
  {
    firstName: 'Ben',
    lastName: 'Wright',
    jobTitle: 'Founder',
    company: 'Pentire Drinks',
    companyType: 'BRAND',
    bio: 'Capturing the Cornish coast in every bottle.',
    location: 'Cornwall',
  },
  {
    firstName: 'Kate',
    lastName: 'Johnson',
    jobTitle: 'Strategy Director',
    company: 'Marillier Consulting',
    companyType: 'SUPPLIER',
    bio: 'Helping drinks brands scale with smart strategy.',
    location: 'London',
  },
  {
    firstName: 'Oliver',
    lastName: 'Davies',
    jobTitle: 'Production Manager',
    company: 'The Custom Spirit Co',
    companyType: 'SUPPLIER',
    bio: 'Bringing spirit concepts to life.',
    location: 'Birmingham',
  },
  {
    firstName: 'Emily',
    lastName: 'Roberts',
    jobTitle: 'Marketing Manager',
    company: 'Three Spirit',
    companyType: 'BRAND',
    bio: 'Plant-powered drinks for elevated evenings.',
    location: 'London',
  },
  {
    firstName: 'Jack',
    lastName: 'Harrison',
    jobTitle: 'Founder',
    company: 'Greenbox Designs',
    companyType: 'SUPPLIER',
    bio: 'Building beautiful websites for drinks brands.',
    location: 'Bristol',
  },
  {
    firstName: 'Megan',
    lastName: 'Price',
    jobTitle: 'Export Manager',
    company: 'Astute Beverages',
    companyType: 'SUPPLIER',
    bio: 'Opening doors to international markets.',
    location: 'London',
  },
  {
    firstName: 'Daniel',
    lastName: 'Hughes',
    jobTitle: 'Co-Founder',
    company: 'Warner\'s Distillery',
    companyType: 'BRAND',
    bio: 'Farm-born spirits from Northamptonshire.',
    location: 'Northamptonshire',
  },
]
