import { EventType, EventStatus } from '@prisma/client'

export const events = [
  // ── Real-world drinks industry events 2026 ──────────────────────────

  {
    title: 'Whisky Live & Fine Spirits London 2026',
    slug: 'whisky-live-london-2026',
    description: 'The industry-renowned whisky tasting event returns to Woolwich Works. Sample an eclectic range of whiskies including limited-edition and rare releases, attend exclusive masterclasses, and enjoy a blending workshop where you can bottle your own personalised whisky blend to take home.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-03-27T11:00:00'),
    endDate: new Date('2026-03-28T18:00:00'),
    isVirtual: false,
    venueName: 'Fireworks Factory at Woolwich Works',
    address: 'Royal Arsenal, No.1 Street',
    city: 'London',
    country: 'United Kingdom',
    capacity: 2000,
    isFree: false,
    price: 55,
    registrationUrl: 'https://www.whiskylive.com/',
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'London Wine Fair 2026',
    slug: 'london-wine-fair-2026',
    description: 'The UK\'s biggest and most loved wine trade fair returns for its 45th edition. Over 10,000 drinks industry professionals are expected at this year\'s fair, which launches the inaugural Host Nation programme spotlighting British drinks — from English sparkling wines to Scottish spirits. Plus, for the first time, BREW//LDN brings a dedicated craft beer and cider space.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-05-18T10:00:00'),
    endDate: new Date('2026-05-20T17:00:00'),
    isVirtual: false,
    venueName: 'Olympia London',
    address: 'Hammersmith Road, Kensington',
    city: 'London',
    country: 'United Kingdom',
    capacity: 10000,
    isFree: false,
    price: 30,
    registrationUrl: 'https://londonwinefair.com/',
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'BCB Brooklyn 2026',
    slug: 'bcb-brooklyn-2026',
    description: 'Bar Convent Brooklyn returns to Industry City with expanded category representation, a strengthened education platform, and enhanced badge experiences. New for 2026, the Workshop Stage introduces a skill-driven environment focused on practical application and deeper exploration of technique and operations. Trade-only event for qualified bar and beverage industry professionals.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-06-09T11:00:00'),
    endDate: new Date('2026-06-10T19:00:00'),
    isVirtual: false,
    venueName: 'Industry City',
    address: '2nd Ave between 33rd & 34th St, Sunset Park',
    city: 'Brooklyn, NY',
    country: 'United States',
    capacity: 5000,
    isFree: false,
    price: 75,
    registrationUrl: 'https://www.barconventbrooklyn.com/',
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'Trade Drinks Expo 2026',
    slug: 'trade-drinks-expo-2026',
    description: 'The UK\'s leading drinks trade exhibition at ExCeL London. Essential for brand owners, distributors, bar groups, independent retailers, and hospitality operators. Discover the latest in production and packaging technologies, pre-mixed cocktails, low-and-no innovations, and premium imports from around 200 exhibitors.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-09-29T10:00:00'),
    endDate: new Date('2026-09-30T17:00:00'),
    isVirtual: false,
    venueName: 'ExCeL London',
    address: 'Royal Victoria Dock, 1 Western Gateway',
    city: 'London',
    country: 'United Kingdom',
    capacity: 3000,
    isFree: false,
    price: 25,
    registrationUrl: 'https://tradedrinksshow.co.uk/',
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'The Whisky Exchange Whisky Show 2026',
    slug: 'whisky-exchange-whisky-show-2026',
    description: 'The UK\'s premier whisky festival returns for its 18th year at Old Billingsgate. A three-day celebration bringing together more than 250 distillers, blenders, and bottlers from around the world with over 1,000 fine whiskies to sample. Includes masterclasses, Q&As, food pairings, cocktails, and the legendary Old & Rare rooms.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-10-02T16:00:00'),
    endDate: new Date('2026-10-04T18:00:00'),
    isVirtual: false,
    venueName: 'Old Billingsgate',
    address: '1 Old Billingsgate Walk',
    city: 'London',
    country: 'United Kingdom',
    capacity: 3000,
    isFree: false,
    price: 85,
    registrationUrl: 'https://whiskyshow.com/',
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'BCB London 2026',
    slug: 'bcb-london-2026',
    description: 'Bar Convent London — formerly Imbibe Live — returns to Tobacco Dock for its second edition. The UK and Ireland\'s essential gathering for the bar and beverage community, featuring over 140 exhibitors, an industry-leading education programme led by director Elliot Ball, and the expanded Local Heroes showcase celebrating homegrown talent.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-10-07T10:00:00'),
    endDate: new Date('2026-10-08T17:00:00'),
    isVirtual: false,
    venueName: 'Tobacco Dock',
    address: 'Tobacco Quay, Wapping Lane',
    city: 'London',
    country: 'United Kingdom',
    capacity: 5000,
    isFree: false,
    price: 25,
    registrationUrl: 'https://www.barconventlondon.com/',
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'BCB Berlin 2026',
    slug: 'bcb-berlin-2026',
    description: 'Bar Convent Berlin celebrates its 20th anniversary as the world\'s largest trade fair for the bar and beverage industry. Over 500 exhibitors from almost 90 countries showcase new spirits, mixers, and bar technologies. Attend live masterclasses, mixology workshops, and tastings led by industry legends across three packed days.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-10-12T10:00:00'),
    endDate: new Date('2026-10-14T18:00:00'),
    isVirtual: false,
    venueName: 'Messe Berlin',
    address: 'Messedamm 22',
    city: 'Berlin',
    country: 'Germany',
    capacity: 15000,
    isFree: false,
    price: 60,
    registrationUrl: 'https://www.barconvent.com/',
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'Athens Bar Show 2026',
    slug: 'athens-bar-show-2026',
    description: 'One of Europe\'s leading educational exhibitions for bartenders and catering professionals, set within the stunning Technopolis complex. Part of Athens Bar Week (1–5 November), the two-day show attracts around 15,000 visitors and transforms the city with non-stop energy, unique experiences, and celebrations across every neighbourhood.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-11-03T11:00:00'),
    endDate: new Date('2026-11-04T19:00:00'),
    isVirtual: false,
    venueName: 'Technopolis City of Athens',
    address: 'Pireos 100, Gazi',
    city: 'Athens',
    country: 'Greece',
    capacity: 15000,
    isFree: false,
    price: 15,
    registrationUrl: 'https://www.athensbarshow.gr/',
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Glasgow\'s Whisky Festival 2026',
    slug: 'glasgows-whisky-festival-2026',
    description: 'Bringing Scotland\'s national drink to Scotland\'s national stadium. Sample hundreds of whiskies from distilleries across Scotland and beyond at Hampden Park. A celebration of whisky culture with tastings, masterclasses, and the chance to meet distillers and brand ambassadors.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-11-07T12:00:00'),
    endDate: new Date('2026-11-07T20:00:00'),
    isVirtual: false,
    venueName: 'Hampden Park',
    address: 'Letherby Drive',
    city: 'Glasgow',
    country: 'United Kingdom',
    capacity: 3000,
    isFree: false,
    price: 35,
    registrationUrl: 'https://glasgowswhiskyfestival.com/',
    showAttendees: true,
    isFeatured: false,
  },

  // ── Kindred Collective community events ─────────────────────────────

  {
    title: 'Kindred Summer Party 2026',
    slug: 'kindred-summer-party-2026',
    description: 'Join us for the biggest Kindred gathering of the year! Network with fellow drinks makers, meet suppliers, and celebrate the independent drinks community. Live music, tastings, and plenty of opportunities to connect.',
    type: 'PARTY' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-07-15T18:00:00'),
    endDate: new Date('2026-07-15T23:00:00'),
    isVirtual: false,
    venueName: 'The Brewery',
    address: '52 Chiswell Street',
    city: 'London',
    country: 'United Kingdom',
    capacity: 300,
    isFree: false,
    price: 45,
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'Kindred Manchester Meetup',
    slug: 'kindred-manchester-meetup-feb-2026',
    description: 'Informal networking drinks for Kindred members in the North. Meet local brands and suppliers, share experiences, and build connections in a relaxed setting.',
    type: 'MEETUP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-02-20T18:30:00'),
    endDate: new Date('2026-02-20T21:00:00'),
    isVirtual: false,
    venueName: 'The Alchemist',
    address: '1 New York Street',
    city: 'Manchester',
    country: 'United Kingdom',
    capacity: 50,
    isFree: true,
    price: null,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Export Masterclass: Breaking into Europe',
    slug: 'export-masterclass-europe-2026',
    description: 'Learn the ins and outs of exporting your drinks to European markets. Covering regulations, logistics, finding distributors, and marketing strategies for international success.',
    type: 'WEBINAR' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-02-05T14:00:00'),
    endDate: new Date('2026-02-05T15:30:00'),
    isVirtual: true,
    venueName: null,
    virtualUrl: 'https://zoom.us/j/example',
    city: 'Online',
    country: 'United Kingdom',
    capacity: 100,
    isFree: true,
    price: null,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Kindred Bristol Meetup',
    slug: 'kindred-bristol-meetup-mar-2026',
    description: 'Connect with Kindred members in the South West. Casual networking drinks at one of Bristol\'s best craft beer venues.',
    type: 'MEETUP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-03-12T18:00:00'),
    endDate: new Date('2026-03-12T21:00:00'),
    isVirtual: false,
    venueName: 'Left Handed Giant Brewpub',
    address: '1 Wadham Street',
    city: 'Bristol',
    country: 'United Kingdom',
    capacity: 40,
    isFree: true,
    price: null,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Brand Launch Bootcamp',
    slug: 'brand-launch-bootcamp-2026',
    description: 'Intensive two-day workshop for drinks entrepreneurs preparing to launch. Covering branding, production, compliance, distribution, and marketing fundamentals.',
    type: 'WORKSHOP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-04-05T09:00:00'),
    endDate: new Date('2026-04-06T17:00:00'),
    isVirtual: false,
    venueName: 'The Trampery',
    address: '239 Old Street',
    city: 'London',
    country: 'United Kingdom',
    capacity: 30,
    isFree: false,
    price: 350,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Sustainable Spirits Summit',
    slug: 'sustainable-spirits-summit-2026',
    description: 'Exploring sustainability across the spirits supply chain. From ingredients to packaging to carbon footprint, learn how leading brands are building a greener future.',
    type: 'WORKSHOP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-09-15T10:00:00'),
    endDate: new Date('2026-09-15T17:00:00'),
    isVirtual: false,
    venueName: 'Here East',
    address: 'Queen Elizabeth Olympic Park',
    city: 'London',
    country: 'United Kingdom',
    capacity: 180,
    isFree: false,
    price: 95,
    showAttendees: true,
    isFeatured: false,
  },
]
