export const newsArticles = [
  {
    title: 'UK Spirits Exports Hit Record High in 2025',
    source: 'The Spirits Business',
    url: 'https://example.com/uk-spirits-exports',
    description: 'British spirits exports reached £5.2 billion in 2025, with gin and whisky leading the charge in international markets.',
    imageUrl: null,
    category: 'Industry News',
    publishedAt: new Date('2026-01-14'),
  },
  {
    title: 'Sustainable Packaging Trends Shaping the Drinks Industry',
    source: 'Packaging World',
    url: 'https://example.com/sustainable-packaging',
    description: 'From recycled glass to paper bottles, drinks brands are embracing innovative eco-friendly packaging solutions.',
    imageUrl: null,
    category: 'Sustainability',
    publishedAt: new Date('2026-01-13'),
  },
  {
    title: 'No/Lo Alcohol Category Sees 30% Growth',
    source: 'The Drinks Business',
    url: 'https://example.com/no-lo-growth',
    description: 'The no and low alcohol segment continues its rapid expansion as health-conscious consumers drive demand.',
    imageUrl: null,
    category: 'Market Trends',
    publishedAt: new Date('2026-01-12'),
  },
  {
    title: 'New Regulations for Online Alcohol Sales Coming in 2026',
    source: 'Morning Advertiser',
    url: 'https://example.com/online-regulations',
    description: 'Government announces new guidelines for age verification and delivery of alcohol purchased online.',
    imageUrl: null,
    category: 'Regulations',
    publishedAt: new Date('2026-01-11'),
  },
  {
    title: 'Craft Distillery Opens in Cornwall, Creates 25 Jobs',
    source: 'Cornwall Live',
    url: 'https://example.com/cornwall-distillery',
    description: 'New artisan distillery launches in Padstow with plans to produce gin and rum using local botanicals.',
    imageUrl: null,
    category: 'New Launches',
    publishedAt: new Date('2026-01-10'),
  },
  {
    title: 'How AI is Transforming Drinks Marketing',
    source: 'Marketing Week',
    url: 'https://example.com/ai-drinks-marketing',
    description: 'From personalized recommendations to automated campaigns, artificial intelligence is reshaping how drinks brands connect with consumers.',
    imageUrl: null,
    category: 'Marketing',
    publishedAt: new Date('2026-01-09'),
  },
  {
    title: 'Budget 2026: What It Means for Drinks Producers',
    source: 'The Grocer',
    url: 'https://example.com/budget-drinks',
    description: 'Analysis of the latest budget announcements and their impact on duty rates for beer, wine, and spirits.',
    imageUrl: null,
    category: 'Regulations',
    publishedAt: new Date('2026-01-08'),
  },
  {
    title: 'English Wine Wins Big at International Competition',
    source: 'Decanter',
    url: 'https://example.com/english-wine-awards',
    description: 'Three English sparkling wines take gold medals at the prestigious Global Wine Awards in London.',
    imageUrl: null,
    category: 'Awards',
    publishedAt: new Date('2026-01-07'),
  },
  {
    title: 'The Rise of Direct-to-Consumer Drinks Sales',
    source: 'Retail Week',
    url: 'https://example.com/dtc-drinks',
    description: 'More drinks brands are bypassing traditional retail to sell directly to consumers through their own websites.',
    imageUrl: null,
    category: 'Market Trends',
    publishedAt: new Date('2026-01-06'),
  },
  {
    title: 'Imbibe Live 2026: What to Expect',
    source: 'Imbibe Magazine',
    url: 'https://example.com/imbibe-live-preview',
    description: 'Preview of the UK\'s biggest on-trade drinks event, featuring over 400 exhibitors and new product launches.',
    imageUrl: null,
    category: 'Events',
    publishedAt: new Date('2026-01-05'),
  },
]
