import { DrinkCategory } from '@prisma/client'

export const brands = [
  {
    name: 'Tarquin\'s Gin',
    slug: 'tarquins-gin',
    tagline: 'Handcrafted Cornish Gin',
    description: 'Tarquin\'s is a pioneering Cornish gin distillery, the first to open in Cornwall since 1913. We handcraft small batches of award-winning gin using a flame-fired copper pot still named Tamara.',
    story: 'Founded by Tarquin Leadbetter in 2012, our distillery sits on the wild north Cornish coast. Every bottle is hand-filled, hand-waxed, and hand-numbered.',
    category: 'SPIRITS' as DrinkCategory,
    subcategories: ['Gin', 'Craft Spirits'],
    yearFounded: 2012,
    location: 'Cornwall',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Brewdog',
    slug: 'brewdog',
    tagline: 'Punk IPA & Craft Beer Revolution',
    description: 'BrewDog is a multinational brewery and pub chain based in Scotland. We\'re on a mission to make other people as passionate about great craft beer as we are.',
    category: 'BEER' as DrinkCategory,
    subcategories: ['IPA', 'Craft Beer', 'Lager'],
    yearFounded: 2007,
    location: 'Aberdeenshire',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Seedlip',
    slug: 'seedlip',
    tagline: 'The World\'s First Distilled Non-Alcoholic Spirit',
    description: 'Seedlip is solving the dilemma of "what to drink when you\'re not drinking". We\'ve created a range of distilled non-alcoholic spirits to revolutionize the way the world drinks.',
    category: 'NO_LO' as DrinkCategory,
    subcategories: ['Non-Alcoholic Spirit', 'Distilled'],
    yearFounded: 2015,
    location: 'London',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Chapel Down',
    slug: 'chapel-down',
    tagline: 'England\'s Leading Winemaker',
    description: 'Chapel Down is England\'s leading wine producer, crafting world-class sparkling and still wines from our vineyards in Kent, the Garden of England.',
    category: 'WINE' as DrinkCategory,
    subcategories: ['Sparkling Wine', 'English Wine'],
    yearFounded: 2001,
    location: 'Kent',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Sipsmith',
    slug: 'sipsmith',
    tagline: 'London\'s First Copper Pot Distillery Since 1820',
    description: 'Sipsmith was founded to bring London Dry Gin back to London. We use traditional copper pot stills to create our award-winning spirits.',
    category: 'SPIRITS' as DrinkCategory,
    subcategories: ['Gin', 'London Dry'],
    yearFounded: 2009,
    location: 'London',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Lucky Saint',
    slug: 'lucky-saint',
    tagline: 'Unfiltered Alcohol-Free Lager',
    description: 'Lucky Saint is an award-winning alcohol-free lager, slow-brewed in Bavaria using just four natural ingredients. Great taste, zero compromise.',
    category: 'NO_LO' as DrinkCategory,
    subcategories: ['Alcohol-Free Beer', 'Lager'],
    yearFounded: 2018,
    location: 'London',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Nc\'nean',
    slug: 'ncnean',
    tagline: 'Organic Scottish Single Malt Whisky',
    description: 'Nc\'nean is Scotland\'s first organic single malt whisky distillery. We\'re pioneering sustainable whisky production on the remote Morvern peninsula.',
    category: 'SPIRITS' as DrinkCategory,
    subcategories: ['Whisky', 'Single Malt', 'Organic'],
    yearFounded: 2017,
    location: 'Morvern',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Toast Ale',
    slug: 'toast-ale',
    tagline: 'Award-Winning Beer Brewed with Surplus Bread',
    description: 'Toast is an award-winning craft beer brewed with surplus fresh bread. We\'re fighting food waste one pint at a time.',
    category: 'BEER' as DrinkCategory,
    subcategories: ['Pale Ale', 'Sustainable Beer'],
    yearFounded: 2016,
    location: 'London',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Three Spirit',
    slug: 'three-spirit',
    tagline: 'Plant-Powered Elixirs',
    description: 'Three Spirit creates functional, botanical drinks designed to elevate your mood and energy, using adaptogens and plants with purpose.',
    category: 'NO_LO' as DrinkCategory,
    subcategories: ['Functional Drinks', 'Non-Alcoholic'],
    yearFounded: 2018,
    location: 'London',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Warner\'s Distillery',
    slug: 'warners-distillery',
    tagline: 'Farm-Born Spirits',
    description: 'Warner\'s is a destination distillery in the heart of Northamptonshire, creating award-winning gin and 0% spirits from farm to bottle.',
    category: 'SPIRITS' as DrinkCategory,
    subcategories: ['Gin', 'Farm Distillery'],
    yearFounded: 2012,
    location: 'Northamptonshire',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Curious Brewery',
    slug: 'curious-brewery',
    tagline: 'Champagne of Beers',
    description: 'Curious Brewery creates unique beers using Champagne yeast and techniques, bridging the gap between beer and wine.',
    category: 'BEER' as DrinkCategory,
    subcategories: ['Craft Beer', 'Lager'],
    yearFounded: 2011,
    location: 'Kent',
    country: 'United Kingdom',
    isVerified: true,
  },
  {
    name: 'Pentire',
    slug: 'pentire',
    tagline: 'Coastal Non-Alcoholic Spirits',
    description: 'Pentire is a non-alcoholic spirit distilled from native Cornish plants, capturing the essence of the north Cornish coast.',
    category: 'NO_LO' as DrinkCategory,
    subcategories: ['Non-Alcoholic Spirit', 'Botanical'],
    yearFounded: 2019,
    location: 'Cornwall',
    country: 'United Kingdom',
    isVerified: true,
  },
]
