import { EventType, EventStatus } from '@prisma/client'

export const events = [
  {
    title: 'Kindred Summer Party 2026',
    slug: 'kindred-summer-party-2026',
    description: 'Join us for the biggest Kindred gathering of the year! Network with fellow drinks makers, meet suppliers, and celebrate the independent drinks community. Live music, tastings, and plenty of opportunities to connect.',
    type: 'PARTY' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-07-15T18:00:00'),
    endDate: new Date('2026-07-15T23:00:00'),
    isVirtual: false,
    venueName: 'The Brewery',
    address: '52 Chiswell Street',
    city: 'London',
    country: 'United Kingdom',
    capacity: 300,
    isFree: false,
    price: 45,
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'Imbibe Live 2026',
    slug: 'imbibe-live-2026',
    description: 'The UK\'s leading on-trade drinks event returns to Olympia London. Discover new products, attend masterclasses, and connect with buyers from bars, restaurants, and hotels across the country.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-07-01T10:00:00'),
    endDate: new Date('2026-07-02T17:00:00'),
    isVirtual: false,
    venueName: 'Olympia London',
    address: 'Hammersmith Road',
    city: 'London',
    country: 'United Kingdom',
    capacity: 5000,
    isFree: false,
    price: 25,
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'Craft Drinks Summit',
    slug: 'craft-drinks-summit-2026',
    description: 'A one-day conference for craft drinks founders and operators. Hear from industry leaders on topics including scaling production, building distribution, and marketing your brand.',
    type: 'WORKSHOP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-08-10T09:00:00'),
    endDate: new Date('2026-08-10T17:00:00'),
    isVirtual: false,
    venueName: 'Manchester Central',
    address: 'Windmill Street',
    city: 'Manchester',
    country: 'United Kingdom',
    capacity: 200,
    isFree: false,
    price: 150,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'London Spirits Competition',
    slug: 'london-spirits-competition-2026',
    description: 'Enter your spirits in one of the most prestigious blind-tasting competitions. Judged by top bartenders, buyers, and spirits experts. Winners receive medals and extensive PR coverage.',
    type: 'OTHER' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-03-15T10:00:00'),
    endDate: new Date('2026-03-16T18:00:00'),
    isVirtual: false,
    venueName: 'St Mary\'s Church',
    address: 'Wyndham Place',
    city: 'London',
    country: 'United Kingdom',
    capacity: 100,
    isFree: false,
    price: 200,
    showAttendees: false,
    isFeatured: false,
  },
  {
    title: 'Kindred Manchester Meetup',
    slug: 'kindred-manchester-meetup-feb-2026',
    description: 'Informal networking drinks for Kindred members in the North. Meet local brands and suppliers, share experiences, and build connections in a relaxed setting.',
    type: 'MEETUP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-02-20T18:30:00'),
    endDate: new Date('2026-02-20T21:00:00'),
    isVirtual: false,
    venueName: 'The Alchemist',
    address: '1 New York Street',
    city: 'Manchester',
    country: 'United Kingdom',
    capacity: 50,
    isFree: true,
    price: null,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Export Masterclass: Breaking into Europe',
    slug: 'export-masterclass-europe-2026',
    description: 'Learn the ins and outs of exporting your drinks to European markets. Covering regulations, logistics, finding distributors, and marketing strategies for international success.',
    type: 'WEBINAR' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-02-05T14:00:00'),
    endDate: new Date('2026-02-05T15:30:00'),
    isVirtual: true,
    venueName: null,
    virtualUrl: 'https://zoom.us/j/example',
    city: 'Online',
    country: 'United Kingdom',
    capacity: 100,
    isFree: true,
    price: null,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Packaging Innovation Forum',
    slug: 'packaging-innovation-forum-2026',
    description: 'Explore the latest trends in sustainable packaging for drinks. Meet suppliers showcasing innovative materials, designs, and solutions for eco-conscious brands.',
    type: 'NETWORKING' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-04-22T10:00:00'),
    endDate: new Date('2026-04-22T16:00:00'),
    isVirtual: false,
    venueName: 'Business Design Centre',
    address: '52 Upper Street',
    city: 'London',
    country: 'United Kingdom',
    capacity: 150,
    isFree: false,
    price: 35,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Scottish Drinks Showcase',
    slug: 'scottish-drinks-showcase-2026',
    description: 'Celebrating Scotland\'s finest independent drinks producers. Tastings, talks, and networking with whisky, gin, beer, and wine makers from across Scotland.',
    type: 'TRADE_SHOW' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-05-18T11:00:00'),
    endDate: new Date('2026-05-19T18:00:00'),
    isVirtual: false,
    venueName: 'Edinburgh International Conference Centre',
    address: '150 Morrison Street',
    city: 'Edinburgh',
    country: 'United Kingdom',
    capacity: 500,
    isFree: false,
    price: 20,
    showAttendees: true,
    isFeatured: true,
  },
  {
    title: 'No/Lo Revolution Conference',
    slug: 'no-lo-revolution-2026',
    description: 'The definitive event for the no and low alcohol drinks sector. Insights on consumer trends, production techniques, and distribution strategies for this fast-growing category.',
    type: 'WORKSHOP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-06-08T09:30:00'),
    endDate: new Date('2026-06-08T17:00:00'),
    isVirtual: false,
    venueName: 'County Hall',
    address: 'Belvedere Road',
    city: 'London',
    country: 'United Kingdom',
    capacity: 250,
    isFree: false,
    price: 125,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Kindred Bristol Meetup',
    slug: 'kindred-bristol-meetup-mar-2026',
    description: 'Connect with Kindred members in the South West. Casual networking drinks at one of Bristol\'s best craft beer venues.',
    type: 'MEETUP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-03-12T18:00:00'),
    endDate: new Date('2026-03-12T21:00:00'),
    isVirtual: false,
    venueName: 'Left Handed Giant Brewpub',
    address: '1 Wadham Street',
    city: 'Bristol',
    country: 'United Kingdom',
    capacity: 40,
    isFree: true,
    price: null,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Brand Launch Bootcamp',
    slug: 'brand-launch-bootcamp-2026',
    description: 'Intensive two-day workshop for drinks entrepreneurs preparing to launch. Covering branding, production, compliance, distribution, and marketing fundamentals.',
    type: 'WORKSHOP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-04-05T09:00:00'),
    endDate: new Date('2026-04-06T17:00:00'),
    isVirtual: false,
    venueName: 'The Trampery',
    address: '239 Old Street',
    city: 'London',
    country: 'United Kingdom',
    capacity: 30,
    isFree: false,
    price: 350,
    showAttendees: true,
    isFeatured: false,
  },
  {
    title: 'Sustainable Spirits Summit',
    slug: 'sustainable-spirits-summit-2026',
    description: 'Exploring sustainability across the spirits supply chain. From ingredients to packaging to carbon footprint, learn how leading brands are building a greener future.',
    type: 'WORKSHOP' as EventType,
    status: 'PUBLISHED' as EventStatus,
    startDate: new Date('2026-09-15T10:00:00'),
    endDate: new Date('2026-09-15T17:00:00'),
    isVirtual: false,
    venueName: 'Here East',
    address: 'Queen Elizabeth Olympic Park',
    city: 'London',
    country: 'United Kingdom',
    capacity: 180,
    isFree: false,
    price: 95,
    showAttendees: true,
    isFeatured: false,
  },
]
