import { OfferType, OfferStatus } from '@prisma/client'

export const offers = [
  {
    supplierSlug: 'label-apeel',
    title: '15% Off First Label Order',
    description: 'New to Label Apeel? Get 15% off your first label order. Premium quality labels with fast turnaround. Minimum order 1,000 labels.',
    type: 'PERCENTAGE_DISCOUNT' as OfferType,
    discountValue: 15,
    code: 'KINDRED15',
    termsConditions: 'Valid for new customers only. Minimum order of 1,000 labels. Cannot be combined with other offers. Valid until March 31, 2026.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-03-31'),
    forBrandsOnly: true,
  },
  {
    supplierSlug: 'saverglass',
    title: 'Free Sampling on Bespoke Projects',
    description: 'Considering a bespoke bottle design? We\'ll provide free samples and 3D renders for qualified projects. Let us bring your vision to life.',
    type: 'FREE_TRIAL' as OfferType,
    termsConditions: 'Subject to project qualification. Minimum projected order of 10,000 units. Contact us to discuss your requirements.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    forBrandsOnly: true,
  },
  {
    supplierSlug: 'buddy-creative',
    title: 'Brand Audit Workshop - £500 Off',
    description: 'Book a comprehensive brand audit workshop and get £500 off our standard rate. Includes competitor analysis, positioning review, and actionable recommendations.',
    type: 'FIXED_DISCOUNT' as OfferType,
    discountValue: 500,
    code: 'KINDREDAUDIT',
    termsConditions: 'Valid for Kindred members only. Must be booked before June 30, 2026. Workshop to be completed within 3 months of booking.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-06-30'),
    forBrandsOnly: true,
  },
  {
    supplierSlug: 'iconic-distro',
    title: '3 Months Free Warehousing',
    description: 'Switch your D2C fulfillment to Iconic Distro and get your first 3 months of warehousing free. Full integration with Shopify, WooCommerce, and Amazon.',
    type: 'FREE_TRIAL' as OfferType,
    termsConditions: 'New customers only. Minimum 12-month contract required. Standard pick and pack fees apply. Setup fee waived.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-06-30'),
    forBrandsOnly: true,
  },
  {
    supplierSlug: 'addition',
    title: '20% Off First Year - Accounting Platform',
    description: 'Get your finances sorted with 20% off your first year on Addition\'s accounting platform. Built specifically for FMCG and e-commerce brands.',
    type: 'PERCENTAGE_DISCOUNT' as OfferType,
    discountValue: 20,
    code: 'KINDRED20',
    termsConditions: 'Valid for new customers only. Annual subscription required. Cannot be combined with other promotions.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    forBrandsOnly: false,
  },
  {
    supplierSlug: 'bb-comms',
    title: 'Free PR Consultation',
    description: 'Book a free 1-hour PR strategy consultation with our spirits specialists. We\'ll review your current approach and identify opportunities for media coverage.',
    type: 'FREE_TRIAL' as OfferType,
    termsConditions: 'One consultation per brand. No obligation to proceed with services. Scheduling subject to availability.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-06-30'),
    forBrandsOnly: true,
  },
  {
    supplierSlug: 'cocktail-connoisseurs',
    title: '10% Off PR Sample Boxes',
    description: 'Launching a new product? Get 10% off our bespoke PR sample boxes. Premium presentation that gets your brand noticed by journalists and influencers.',
    type: 'PERCENTAGE_DISCOUNT' as OfferType,
    discountValue: 10,
    code: 'KINDREDPR',
    termsConditions: 'Minimum order of 25 boxes. Valid for new and existing customers. Cannot be combined with volume discounts.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-04-30'),
    forBrandsOnly: true,
  },
  {
    supplierSlug: 'custom-spirit-co',
    title: 'Free Recipe Development Session',
    description: 'Thinking of creating a new spirit? Get a free recipe development session with our master distiller. We\'ll help you refine your concept and create samples.',
    type: 'FREE_TRIAL' as OfferType,
    termsConditions: 'Subject to project viability assessment. Production contract required if proceeding. One session per brand.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    forBrandsOnly: true,
  },
  {
    supplierSlug: 'greenbox-designs',
    title: '£300 Off Website Projects',
    description: 'Ready for a new website? Get £300 off any web design or development project. From simple updates to complete rebuilds.',
    type: 'FIXED_DISCOUNT' as OfferType,
    discountValue: 300,
    code: 'KINDREDWEB',
    termsConditions: 'Valid for projects over £2,000. New and existing customers. Must be booked by May 31, 2026.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-05-31'),
    forBrandsOnly: false,
  },
  {
    supplierSlug: 'scale-drinks',
    title: 'Free Export Market Assessment',
    description: 'Wondering which international markets suit your brand? Get a free export market assessment identifying your top 3 target markets with entry strategies.',
    type: 'FREE_TRIAL' as OfferType,
    termsConditions: 'One assessment per brand. Report delivered within 2 weeks. No obligation to proceed with export services.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    forBrandsOnly: true,
  },
  {
    supplierSlug: 'clyde-presentation-packaging',
    title: '15% Off Gift Box Orders',
    description: 'Premium gift packaging at a premium discount. Get 15% off presentation boxes, cases, and bespoke packaging solutions.',
    type: 'PERCENTAGE_DISCOUNT' as OfferType,
    discountValue: 15,
    code: 'KINDREDGIFT',
    termsConditions: 'Minimum order 100 units. Valid for new orders only. Cannot be combined with other offers.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-03-31'),
    forBrandsOnly: true,
  },
  {
    supplierSlug: 'london-city-bond',
    title: 'First Month Storage Free',
    description: 'Move your stock to our bonded warehouse and get your first month of storage completely free. Full duty management and UK-wide delivery available.',
    type: 'FREE_TRIAL' as OfferType,
    termsConditions: 'New customers only. Minimum 6-month agreement required. Handling fees apply from month one.',
    status: 'ACTIVE' as OfferStatus,
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-06-30'),
    forBrandsOnly: true,
  },
]
