-- Kindred Collective Supplier Import
-- Generated from scraping kindredcollective.co.uk
-- Date: 2026-01-17T18:09:10Z

-- First, delete existing suppliers and related data
DELETE FROM "SavedSupplier";
DELETE FROM "Offer";
DELETE FROM "SupplierReview";
DELETE FROM "Supplier";

-- Insert scraped suppliers

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Addition',
  'addition',
  'Accounting & CFO Platform for FMCG/Ecom businesses.',
  'Accounting & CFO Platform for FMCG/Ecom businesses.',
  'FINANCE',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture3_5ed61f04-3cfa-41cc-a016-a1f21d4857e2.png?v=1751028399',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'AM Distilling LTD',
  'am-distilling-ltd',
  'We are a small-medium sized contract bottler based just outside London.',
  'We are a small-medium sized contract bottler based just outside London. We offer Bottling, Blending, Compounding, rectification, cask filling, cask storage, whisky blending up to 100k liters as well as sourcing bulk spirits from around the world. We offer the following spirit types Whisky, Scotch Whisky (inc single malt), Rum, Vodka, Gin, Tequila (CRT certified), liqueurs, brandy and Neutral Grain Spirit. Low MOQs (500 units). As a contract bottler we also are able to source at great rates Glass, Corks (custom design), Shrink Caps & Cardboard Transit Cases.',
  'CO_PACKING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/BlackBridgeDistillery.png?v=1760618825',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Anderson Cole Group',
  'anderson-cole-group',
  'Anderson Cole Group is a UK-based boutique recruitment consultancy launched in late 2024.',
  'Anderson Cole Group is a UK-based boutique recruitment consultancy launched in late 2024. They specialise in matching top-tier talent with forward-thinking organisations, particularly in the education, media, and FMCG sectors. With a personal, relationship-driven approach, Anderson Cole handles everything from permanent to interim and executive placements, ensuring not just a skills fit but also cultural alignment with each client’s brand. Founded and led by Tom Cole, the firm positions itself as a true extension of its clients, building long-term partnerships that go beyond mere transactions. They are already recruiting for finance and admin roles across southern England.',
  'RECRUITMENT',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture5.png?v=1751023023',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Astute Beverages',
  'astute-beverages',
  'Regulatory and Compliance, Label Reviews, FSVP workflow, Import and Distribution Strategy',
  'Regulatory and Compliance, Label Reviews, FSVP workflow, Import and Distribution Strategy',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/AstuteBeverages.png?v=1760620711',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Avallen Solutions',
  'avallen-solutions',
  'Sustainability strategy, advice, and support',
  'Sustainability strategy, advice, and support',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Green_Background-Winner-Avallen_Solutions.png?v=1749570994',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'B2C Group Ltd',
  'b2c-group-ltd',
  'Distribution, Bonded Warehousing, Logistics, E-commerce, B2B, Brand Strategy & Development, Advertising & Performance Marketing, Compliance & Internat',
  'Distribution, Bonded Warehousing, Logistics, E-commerce, B2B, Brand Strategy & Development, Advertising & Performance Marketing, Compliance & International Expansion',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture17.png?v=1752091278',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'BB Comms',
  'bb-comms',
  'Public Relations in US, UK & internationallyMarketing planning and strategyEvents concept creation and execution',
  'Public Relations in US, UK & internationallyMarketing planning and strategyEvents concept creation and execution',
  'PR',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/BBComms.png?v=1760623040',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'BBJ&K',
  'bbj-k',
  'Paid Media: Above The Line (TV, Radio, Out of Home, Print) & Digital (Paid Social, Google/Amazon PPC, Connected TV, YouTube, Display, In-Game, Podcast',
  'Paid Media: Above The Line (TV, Radio, Out of Home, Print) & Digital (Paid Social, Google/Amazon PPC, Connected TV, YouTube, Display, In-Game, Podcasts, Digital Audio, Digital Out of Home + more). We also have special relationships partner agencies for a full suite of Creative/Design/Audience Insights services. ',
  'DESIGN',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/BBJ-K-logo-profile.png?v=1749569658',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Berlin Packaging',
  'berlin-packaging',
  'Berlin Packaging is the World's Largest Hybrid Packaging Supplier in glass, plastic, metal packaging, and closures.',
  'Berlin Packaging is the World's Largest Hybrid Packaging Supplier in glass, plastic, metal packaging, and closures. The company is a One-Stop Packaging Shop that brings together the best elements of Design & Innovation, Manufacturing Services, and Customer Solutions for the packaging industry. It is the only player that can offer such a complete range of services and supports clients during the entire packaging cycle.',
  'PACKAGING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/brunierben_logo.png?v=1749567681',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Bobbys Gin Distribution BV',
  'bobbys-gin-distribution-bv',
  'Gin , Jenever,  Ready To drink cocktails',
  'Gin , Jenever,  Ready To drink cocktails',
  'DISTRIBUTION',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Bobby_sGin.png?v=1749568586',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Bostocap SRL',
  'bostocap-srl',
  'Bottle Stoppers and Capsules',
  'Bottle Stoppers and Capsules',
  'OTHER',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture4_d3087a84-c028-4ab5-b662-e6866b22aff8.png?v=1751028533',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Bowimi',
  'bowimi',
  'BOWIMI is a CRM/Sales Platform specifically for drink brands to better record, organise and act on sales data.',
  'BOWIMI is a CRM/Sales Platform specifically for drink brands to better record, organise and act on sales data.  BOWIMI is a bit like merging google maps, a CRM and all your excel spreadsheets (although I'm sure our tech geniuses wouldn't be happy with me describing the platform this way). We strip out time wasting admin, making the team more productive and customer focussed. Our live dashboards allow exec teams to be able monitor performance and gain incredible actionable insights in trade activities with one simple click of a button. Manage your customers, prospects, route planning, data capture, ordering, sales performance, surveys, listing types, track sampling, ambassador activity, activations, contracts, reporting and much more, all from the palm of your hand. On average BOWIMI users gain 4 working days back a month from the efficiencies of using the platform.',
  'OTHER',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/images_7666c97f-1723-4f8a-89ea-e54f395dd7d1.png?v=1749570880',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Buddy Creative',
  'buddy-creative',
  'From full-blown global identity projects to local start-ups, we specialise in food, drink and lifestyle brands for the likes of Molson Coors and South',
  'From full-blown global identity projects to local start-ups, we specialise in food, drink and lifestyle brands for the likes of Molson Coors and SouthWestern Distillery ',
  'DESIGN',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/BuddyCreative.jpg?v=1765918416',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Burlington Bottling Co.',
  'burlington-bottling-co',
  'Contract Bottling',
  'Contract Bottling',
  'CO_PACKING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Burlington.png?v=1749571424',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Cleverdrinks Photography',
  'cleverdrinks-photography',
  'Photography & Videography',
  'Photography & Videography',
  'PHOTOGRAPHY',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Clever_4-3.png?v=1749567849',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Clyde Presentation Packaging',
  'clyde-presentation-packaging',
  'Based in Glasgow, we design and produce a full range of bespoke presentation packaging, covering cartons, rigid boxes, tubes and wooden boxes, all of ',
  'Based in Glasgow, we design and produce a full range of bespoke presentation packaging, covering cartons, rigid boxes, tubes and wooden boxes, all of which help your product stand out in the market. Whether you want to launch a limited edition product or have a high volume ongoing need then speak to us today to discuss your requirement.',
  'PACKAGING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/ClydePackaging.png?v=1749570746',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Cocktail Connoisseurs',
  'cocktail-connoisseurs',
  'Bring Your Brand to Life with Bespoke PR Boxes & Custom Kits Elevate your brand with our fully bespoke drinks experience—premium custom branded boxe',
  'Bring Your Brand to Life with Bespoke PR Boxes & Custom Kits Elevate your brand with our fully bespoke drinks experience—premium custom branded boxes and bespoke gift sets meticulously tailored for brand activations, personalised PR boxes, hospitality events, and luxury corporate gifting. Each bespoke gift set is thoughtfully designed and handcrafted, creating a distinctive branded experience that leaves a lasting impression.',
  'PR',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture3.png?v=1751021264',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Cone Accounting Limited',
  'cone-accounting-limited',
  'Cone is a modern, cloud-based accountancy practice founded in 2015, with offices in Hampshire and London.',
  'Cone is a modern, cloud-based accountancy practice founded in 2015, with offices in Hampshire and London. They specialise in supporting creative, hospitality, and e‑commerce entrepreneurs, offering more than just compliance—they partner with clients as virtual financial directors to drive real growth . Their services include: converting financial transactions into clear, actionable reports; strategic growth planning tailored to client‑specific goals; comprehensive tax, payroll, HMRC and Companies House compliance; and a fully paper‑free, mobile-friendly workflow using Xero, with subscription included . Cone emphasises transparency, freedom, creativity, and a “people-first” ethos—working remotely with clients via discovery calls, quarterly reviews, and ongoing support to help small businesses thrive .',
  'FINANCE',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture4.png?v=1751021920',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Cooper Parry',
  'cooper-parry',
  'Accountancy Services',
  'Accountancy Services',
  'OTHER',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/download_c9b3a44c-c405-4c79-8f42-5c3de17b0b01.png?v=1749567591',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Crate PR',
  'crate-pr',
  'PR, marketing and influencer engagement services ',
  'PR, marketing and influencer engagement services ',
  'PR',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/CC-StackedLogo_Orange_646c9e1b-3489-4910-8c7a-efe4f3f58563.png?v=1749570683',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Cutlass Communications',
  'cutlass-communications',
  'PR, Event, Media Buying, Marketing, On-trade Marketing, Trade Show Stands',
  'PR, Event, Media Buying, Marketing, On-trade Marketing, Trade Show Stands',
  'PR',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Cutlass.png?v=1749569122',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'DIGLIS Consulting',
  'diglis-consulting',
  'Recruitment, Talent Planning, Salary and Benefits advice, Headhunting and Consultancy',
  'Recruitment, Talent Planning, Salary and Benefits advice, Headhunting and Consultancy',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture13.png?v=1752074983',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Dimax Digital',
  'dimax-digital',
  'Digital Marketing and Brand Development',
  'Digital Marketing and Brand Development',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Dimax.png?v=1749569428',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'DrincX Ltd.',
  'drincx-ltd',
  'Brand management, business development & consulting',
  'Brand management, business development & consulting',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture1_7364d665-7aa2-4dd7-83a7-e255041d029c.png?v=1751028234',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Easy Chew',
  'easy-chew',
  'Paid Ads - Social Media & Search Full presentation available by Kindred Nas.',
  'Paid Ads - Social Media & Search Full presentation available by Kindred Nas.io back end under Digital Services',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/EasyChew_Logo_RGB_Normal_Charcoal_ec6ac811-6aa5-4a98-8b87-b98acf08d387.png?v=1749557383',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Flourish Creative',
  'flourish-creative',
  'We create studio and lifestyle content that brings your brand to life through vibrant photography and engaging video.',
  'We create studio and lifestyle content that brings your brand to life through vibrant photography and engaging video. From product shoots and behind-the-scenes storytelling to on-location content at distilleries, bars, restaurants, or out in the beautiful Cornish landscape. We capture the moments that connect your brand to your audience.',
  'PHOTOGRAPHY',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture1.png?v=1749630494',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Frederick Wilkinson',
  'frederick-wilkinson',
  'Photography and Videography',
  'Photography and Videography',
  'PHOTOGRAPHY',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture8.png?v=1751025970',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Giraffe Distillers Ltd',
  'giraffe-distillers-ltd',
  'Sustainability focused Contract Bottling, Distilling, Blending and Liquid Development for spirit based products.',
  'Sustainability focused Contract Bottling, Distilling, Blending and Liquid Development for spirit based products. Bottling of various sizes, shapes, formats and closures from 2ml - 3ltr including glass, aluminium,  pouches and bulk liquid. Manual low volume, white glove production through to high volume automated daily production. Branded bottling, white and private label and NPD development all undertaken.  Organic Soil Association and food production site accreditations, bonded facility and short term storage.   ',
  'CO_PACKING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/1681740050921.png?v=1749567428',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Graceful Monkey',
  'graceful-monkey',
  'Multidiscipline creative - we work out the best creative solution to achieve your goal, using CGI / Stills / Retouch / Animation / Live Action / Inter',
  'Multidiscipline creative - we work out the best creative solution to achieve your goal, using CGI / Stills / Retouch / Animation / Live Action / Interactive / VR / AR.  We blend creative excellence + technical efficiency to deliver brand impact and reliable delivery.  Our passion lies in creating future focused scalable creative systems - maximising use of assets giving them longevity and delivering value. Including toolkits and custom build libraries. ',
  'OTHER',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/GracefulMonkey.jpg?v=1765918843',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Greenbox Designs',
  'greenbox-designs',
  'The one and only website builder for the Kindred group!',
  'The one and only website builder for the Kindred group!',
  'OTHER',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/logogreenbox_002.png?v=1749629844',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Halo Business Support Ltd',
  'halo-business-support-ltd',
  'Back-office logistics - operational support, order processing, invoicing, customer service, social media and production',
  'Back-office logistics - operational support, order processing, invoicing, customer service, social media and production',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/images_2_3dbfe0d0-a634-4916-b2dd-053fde4fcdda.png?v=1749557613',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Hensol Castle Distillery',
  'hensol-castle-distillery',
  'Contract Bottling, Contract Distilling, New Product Development.',
  'Contract Bottling, Contract Distilling, New Product Development. ',
  'CO_PACKING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/HensolCastle.png?v=1749569035',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'HighSpirit Agency',
  'highspirit-agency',
  'HighSpirit is a next-gen creative agency for premium drinks brands.',
  'HighSpirit is a next-gen creative agency for premium drinks brands. We provide 360 creative support from naming and packaging to campaigns and digital, giving you total confidence and consistency across all channels.',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture19.jpg?v=1752091963',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Iconic Distro Company Ltd',
  'iconic-distro-company-ltd',
  'D2C Fulfilment, D2C Management, Amazon Account Management, ECommerce Account Management, NED, Business Coaching, Business Advice, Brand Distribution',
  'D2C Fulfilment, D2C Management, Amazon Account Management, ECommerce Account Management, NED, Business Coaching, Business Advice, Brand Distribution',
  'DISTRIBUTION',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/iconic_distro_co_ltd_logo.png?v=1749570317',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Kind Community',
  'kind-community',
  'AI has made it easier than ever to start a business, create content and ads.',
  'AI has made it easier than ever to start a business, create content and ads. But harder than ever to build trust.Like you, your customers crave connection, not just content.KIND helps you build a movement, not just marketing funnels.Because brands that show up in person, win loyalty that lasts.',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture20.jpg?v=1752093552',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Label Apeel Ltd',
  'label-apeel-ltd',
  'We are a multi award-winning printer and manufacturer of self-adhesive labels and have an unrivalled reputation for working within the beers, wines an',
  'We are a multi award-winning printer and manufacturer of self-adhesive labels and have an unrivalled reputation for working within the beers, wines and spirits, food, supplement, and personal care sectors.',
  'PACKAGING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture14.png?v=1752075767',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'London City Bond Ltd.',
  'london-city-bond-ltd',
  'Bonded warehouse storage and delivery / distribution to Trade, Grocer, Amazon, D2C across the UK from any of our 16 bonded locations.',
  'Bonded warehouse storage and delivery / distribution to Trade, Grocer, Amazon, D2C across the UK from any of our 16 bonded locations.',
  'DISTRIBUTION',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture2.png?v=1749630618',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Lucie Rhoades Comms',
  'lucie-rhoades-comms',
  'Copywriting and brand consultancy',
  'Copywriting and brand consultancy',
  'PR',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture2_e8f4cc57-fb92-4c4d-b9f6-bc7f3b0bb62b.png?v=1751028320',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'MAFFEO DRINKS s.r.o.',
  'maffeo-drinks-s-r-o',
  'Commercial & Marketing Advisory',
  'Commercial & Marketing Advisory',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/9374e364-300f-4051-abff-9fa74dee365e_1506x850_17d7be92-e79c-4dcb-8e71-e7e2b514eb09.png?v=1749567973',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Marillier Consulting',
  'mariller',
  'Drinks industry consulting, specialising in long term planning, strategy, financial planning and distribution focused on helping businesses unlock pro',
  'Drinks industry consulting, specialising in long term planning, strategy, financial planning and distribution focused on helping businesses unlock problems and so focus on their drivers of growth',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture12.png?v=1752074641',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Marillier Consulting',
  'marillier-consulting',
  'Drinks industry consulting, specialising in long term planning, strategy, financial planning and distribution focused on helping businesses unlock pro',
  'Drinks industry consulting, specialising in long term planning, strategy, financial planning and distribution focused on helping businesses unlock problems and so focus on their drivers of growth',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/38cc2f7d-214d-471c-afd2-83da053bcce1_878e1685-552b-4d38-97e2-1e32bfe894b0.png?v=1749571487',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Midday Studio',
  'midday-studio',
  'Midday is an award-winning design studio specialising in food, drink, and lifestyle brands "” worldwide.',
  'Midday is an award-winning design studio specialising in food, drink, and lifestyle brands "” worldwide.',
  'OTHER',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Midday-6.png?v=1749569987',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Nightcap Brands',
  'nightcap-brands',
  'A specialist Sales Agency and distributor, driving sales in both on-trade and retail for a selection of premium drinks brands.',
  'A specialist Sales Agency and distributor, driving sales in both on-trade and retail for a selection of premium drinks brands. ',
  'OTHER',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/071a93eb-7883-49fe-b6aa-5c266cf3b6a4_1.png?v=1749568188',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Nolen Consultancy',
  'nolen-consultancy',
  'drinks industry consultancy',
  'drinks industry consultancy',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/1724247284154_0a613a14-61d9-4738-8d13-b6b043904559.jpg?v=1749630077',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'On A Plate Growth',
  'on-a-plate-growth',
  'Email Marketing, CRM, DTC Sales Growth, Virtual Co-Founder/Sounding Board, 1:1 Support.',
  'Email Marketing, CRM, DTC Sales Growth, Virtual Co-Founder/Sounding Board, 1:1 Support.',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/OnaPlate.png?v=1749570090',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Orange by Marmalade',
  'orange-by-marmalade',
  'We provide brand strategy, activation and partnership services to help brands define their unique place in the world and express it with a compelling ',
  'We provide brand strategy, activation and partnership services to help brands define their unique place in the world and express it with a compelling positioning, narrative, beautifully-crafted design',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Orange_Marmalade_Logo-01_c221c308-f483-4b93-8041-8bc23bad1d7d.png?v=1749567761',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Partner Up',
  'partner-up',
  'A platform for brands to connect with like-minded brands for mutually beneficial marketing collaborations and partnerships',
  'A platform for brands to connect with like-minded brands for mutually beneficial marketing collaborations and partnerships',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/PartnerUp.png?v=1749569800',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Pear & Sons Production Studio',
  'pear-sons-production-studio',
  'Purpose driven visual assets - Experts in food and drink',
  'Purpose driven visual assets - Experts in food and drink',
  'PHOTOGRAPHY',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/pear_sons_logo-07_copy_31e949f6-eaea-457e-a691-579d3af95a8a.png?v=1749570591',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Propak UK',
  'propak-uk',
  'Luxury Branded Packaging, as well as more generic day to day consumables.',
  'Luxury Branded Packaging, as well as more generic day to day consumables. Eg. Presentation Boxes, Magnetic Boxes, Gift Bags, Tissue, Warehouse consumables, Barware, Tin.',
  'PACKAGING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Propak.png?v=1749571305',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Red Distillery',
  'red-distillery',
  'Bottling, Canning, Packing, Procurement, Blending, Development, Distribution and Fulfilment.',
  'Bottling, Canning, Packing, Procurement, Blending, Development, Distribution and Fulfilment. We can offer expert advice in all areas as well as supporting your business with a number of operations.',
  'DISTRIBUTION',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture18.png?v=1752091766',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'SAVERGLASS',
  'saverglass',
  'Manufacturer and decorator of high-quality glass bottles, offering both off-the-shelf and bespoke solutions.',
  'Manufacturer and decorator of high-quality glass bottles, offering both off-the-shelf and bespoke solutions.',
  'PACKAGING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/SaverGlass.png?v=1760620378',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'SBP Events LTD',
  'sbp-events-ltd',
  'We pride ourselves in making sure our clients arrive at the shows in the best possible location, relaxed and ready to trade and obtain their targets a',
  'We pride ourselves in making sure our clients arrive at the shows in the best possible location, relaxed and ready to trade and obtain their targets and expectations. Whether it be our large marquees or small bespoke stand alone marquees for individual brands, there is always a ‘carpeted’ wooden floor to keep out the elements. In our large communal marquees we also supply full shell scheme Velcro compatible walls and electrics. As one of the leading event providers of space on agricultural events our experience as exhibitors ourselves makes us stand out from most of our competitors, as we know exactly what one expects from shows and exhibitions  ',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture2_dd6dfc39-0b80-4b8c-8da8-3777f5e0500f.png?v=1751020674',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Scale Drinks',
  'scale-drinks',
  '- Access to 60+ countries- Relationships with Proven importers and Distributors- Bespoke export strategy planning- Market Research- Importer managemen',
  '- Access to 60+ countries- Relationships with Proven importers and Distributors- Bespoke export strategy planning- Market Research- Importer management and performance reviews- Financial security - insurance, currency investment, credit checks- Uk gov support and grants available- Inco terms and pricing strategy - Simplifying global route to market',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture16.png?v=1752091109',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Seven Sages',
  'seven-sages',
  'Marketing, Design & Editing Services',
  'Marketing, Design & Editing Services',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/SevenSages.png?v=1749568715',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Smurfit Westrock Saxon',
  'smurfit-westrock-saxon',
  'Corrugated boxes ',
  'Corrugated boxes ',
  'OTHER',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Smurfit.png?v=1749569490',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Soho Drinks Ltd',
  'soho-drinks-ltd',
  'With over 25 years of Drinks and Lifestyle PR experience, Soho Drinks works with brands to raise their profiles',
  'With over 25 years of Drinks and Lifestyle PR experience, Soho Drinks works with brands to raise their profiles',
  'PR',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/SohoDrinks.png?v=1749569907',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Spirited Marketing',
  'spirited-marketing',
  '',
  '',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/SB-650x650-12-3_51d63abf-9a7d-4d4e-9aa5-50914275f27d.png?v=1749570244',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Supplychain21 Ltd',
  'supplychain21-ltd',
  'We’re a specialist freight forwarder dedicated to supporting the drinks industry.',
  'We’re a specialist freight forwarder dedicated to supporting the drinks industry.Whether you’re moving alcohol, soft drinks, bottles, packaging, raw materials, or even promotional items, we’re here to help at every stage of your supply chain.We also have our own UK movement guarantee, which means we can assist with both duty suspended and duty paid shipments. Our services cover everything from UK and cross-border transport to overnight pallets, same-day deliveries, loose casks, hazardous cargo, groupage, part and full trailer loads, consolidation, sea containers and air freight.If you’d like to know more or have any questions, please do get in touch.',
  'PACKAGING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/SupplyChain21.png?v=1760622791',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'The Advocate Group',
  'the-advocate-group',
  'Recruitment, Growth Acceleration, Branded Marketing Campaigns',
  'Recruitment, Growth Acceleration, Branded Marketing Campaigns',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/AdvocateGroup.png?v=1749569577',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'The Brand Weaver',
  'the-brand-weaver',
  'Brand Strategy, Consultancy & Design',
  'Brand Strategy, Consultancy & Design',
  'CONSULTING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/brand-weaver-cap-front_fd8fa725-7691-4ad0-9ea5-5a1056e1178c.png?v=1749571241',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'The Custom Spirit Co.',
  'the-custom-spirit-co',
  'Contract distilling, blending, fermentation and bottling.',
  'Contract distilling, blending, fermentation and bottling. New product development & product reformulation for cost and supply chain optimisation',
  'CO_PACKING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/Picture7.png?v=1751025789',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'This is Undefined',
  'this-is-undefined',
  'We design & build website (shopify & content websites) + digital products',
  'We design & build website (shopify & content websites) + digital products',
  'OTHER',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/undefined_yellow_63124417-b92b-424e-8ec6-adea6ce9df4f.png?v=1749568901',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Tortuga',
  'tortuga',
  'UK Distribution.',
  'UK Distribution. Outsourced Back Office Distribution Services of an Order Office team, Operations, Finance & Credit Control, duty suspended storage with national delivery. We have open accounts with the majority of wholesalers and retailers in the UK, including key Grocers (such as Waitrose, Sainsbury's, Co-op etc) helping to provide access and less barriers to trading with them. Live visibility of stock levels and customer orders through our Client Portal and App. Tortuga handles the back office distribution, while brand owners do the sales & marketing. ',
  'MARKETING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/220b10b9-8c41-430f-843b-30da6f01fd93_b78dffd6-412e-4f58-a8db-e063b92e65a8.png?v=1749570384',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

INSERT INTO "Supplier" (
  id,
  "companyName",
  slug,
  tagline,
  description,
  category,
  services,
  "logoUrl",
  "isPublic",
  "isVerified",
  "claimStatus",
  "viewCount",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'Verallia',
  'verallia',
  'UK made Bottles; bespoke & off the shelf.',
  'UK made Bottles; bespoke & off the shelf. Glass bottle decoration. ',
  'PACKAGING',
  '{}',
  'https://cdn.shopify.com/s/files/1/0924/3095/8923/files/verallia.png?v=1749571118',
  true,
  false,
  'UNCLAIMED',
  0,
  NOW(),
  NOW()
);

-- Done! Imported 64 suppliers
